# Spring boot application
spring:
  application:
    name: myshop-api-gateway
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
server:
  port: 9000

# Services Versions
services:
  ports:
    user:
      port: 8601
    content:
      port: 8602
  versions:
    content:
      v1: 1.0.0
    user:
      v1: 1.0.0

# Dubbo Config properties
dubbo:
  scan:
    basePackages: com.pxxy.api.gateway
  ## ApplicationConfig Bean
  application:
    id: myshop-api-gateway
    name: myshop-api-gateway
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 40881
    status: server
    serialization: kryo
  ## RegistryConfig Bean
  registry:
    id: zookeeper
    address: zookeeper://47.100.18.197:2181

# Dubbo Endpoint (default status is disable)
endpoints:
  dubbo:
    enabled: true

management:
  server:
    port: 9001
  # Dubbo Health
  health:
    dubbo:
      status:
        ## StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
  # Enables Dubbo All Endpoints
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

# Apollo
apollo:
  bootstrap:
    enabled: true
    # will inject 'application' and 'TEST1.apollo' namespaces in bootstrap phase
    namespaces: application
